import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfGeneratorService {
  static final primaryPurple = PdfColor.fromHex('#7051C7');
  static final primaryPink = PdfColor.fromHex('#F65E87');
  static final textDark = PdfColor.fromHex('#302A3A');
  static final textSecondary = PdfColor.fromHex('#8A8194');
  static final borderCol = PdfColor.fromHex('#E7DFEC');
  static final bgPink = PdfColor.fromHex('#FFF0F5');

  static Future<Uint8List> generateDoctorReport() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (pw.Context context) {
          return [
            _buildHeader(),
            pw.SizedBox(height: 12),
            _buildPatientInfo(),
            pw.SizedBox(height: 12),
            _buildReportOverview(),
            pw.SizedBox(height: 12),
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(child: _buildCycleSummaryChart()),
                pw.SizedBox(width: 16),
                pw.Expanded(child: _buildPeriodDetailsChart()),
              ],
            ),
            pw.SizedBox(height: 12),
            _buildSymptomsAndMoodTables(),
            pw.SizedBox(height: 12),
            _buildLifestyleInsights(),
            pw.SizedBox(height: 12),
            _buildObservations(),
            pw.SizedBox(height: 16),
            pw.Center(
              child: pw.Text(
                'Generated by Bloom App on Aug 22, 2026',
                style: pw.TextStyle(color: textSecondary, fontSize: 8),
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader() {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: pw.BoxDecoration(
        color: bgPink,
        border: pw.Border(left: pw.BorderSide(color: primaryPink, width: 4)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Bloom Medical Report',
                style: pw.TextStyle(color: primaryPurple, fontWeight: pw.FontWeight.bold, fontSize: 16),
              ),
              pw.SizedBox(height: 2),
              pw.Text(
                'Confidential Patient Data',
                style: pw.TextStyle(color: primaryPink, fontSize: 10),
              ),
            ],
          ),
          pw.Text(
            'Date Range: Feb 1 - Jul 31, 2026 (6 cycles)',
            style: pw.TextStyle(color: textDark, fontSize: 10, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPatientInfo() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Patient Information'),
        pw.SizedBox(height: 8),
        pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: borderCol),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _buildInfoCol('Name', 'Ananya Sharma'),
              _buildInfoCol('Age', '24'),
              _buildInfoCol('DOB', '12 Jan 2002'),
              _buildInfoCol('Height', '165 cm'),
              _buildInfoCol('Weight', '60 kg'),
              _buildInfoCol('Blood Group', 'O+'),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildReportOverview() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Key Metrics Overview'),
        pw.SizedBox(height: 8),
        pw.Row(
          children: [
            pw.Expanded(child: _buildMetricBox('29 days', 'Avg. Cycle')),
            pw.SizedBox(width: 8),
            pw.Expanded(child: _buildMetricBox('28 days', 'Shortest Cycle')),
            pw.SizedBox(width: 8),
            pw.Expanded(child: _buildMetricBox('31 days', 'Longest Cycle')),
            pw.SizedBox(width: 8),
            pw.Expanded(child: _buildMetricBox('±2 days', 'Cycle Variation')),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Row(
          children: [
            pw.Expanded(child: _buildMetricBox('5 days', 'Avg. Period')),
            pw.SizedBox(width: 8),
            pw.Expanded(child: _buildMetricBox('4 days', 'Shortest Period')),
            pw.SizedBox(width: 8),
            pw.Expanded(child: _buildMetricBox('6 days', 'Longest Period')),
            pw.SizedBox(width: 8),
            pw.Expanded(child: _buildMetricBox('Moderate', 'Average Pain')),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildCycleSummaryChart() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Cycle Length History'),
        pw.SizedBox(height: 8),
        pw.Container(
          height: 120,
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(border: pw.Border.all(color: borderCol)),
          child: pw.Chart(
            grid: pw.CartesianGrid(
              xAxis: pw.FixedAxis([1, 2, 3, 4, 5, 6], format: (v) => 'C${v.toInt()}', textStyle: pw.TextStyle(fontSize: 8)),
              yAxis: pw.FixedAxis([0, 7, 14, 21, 28, 35], textStyle: pw.TextStyle(fontSize: 8)),
            ),
            datasets: [
              pw.BarDataSet(
                color: primaryPink,
                width: 20,
                data: [
                  const pw.PointChartValue(1, 28),
                  const pw.PointChartValue(2, 30),
                  const pw.PointChartValue(3, 29),
                  const pw.PointChartValue(4, 31),
                  const pw.PointChartValue(5, 30),
                  const pw.PointChartValue(6, 29),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildPeriodDetailsChart() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Period Length History'),
        pw.SizedBox(height: 8),
        pw.Container(
          height: 120,
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(border: pw.Border.all(color: borderCol)),
          child: pw.Chart(
            grid: pw.CartesianGrid(
              xAxis: pw.FixedAxis([1, 2, 3, 4, 5, 6], format: (v) => 'C${v.toInt()}', textStyle: pw.TextStyle(fontSize: 8)),
              yAxis: pw.FixedAxis([0, 2, 4, 6, 8, 10], textStyle: pw.TextStyle(fontSize: 8)),
            ),
            datasets: [
              pw.BarDataSet(
                color: primaryPurple,
                width: 20,
                data: [
                  const pw.PointChartValue(1, 4),
                  const pw.PointChartValue(2, 5),
                  const pw.PointChartValue(3, 5),
                  const pw.PointChartValue(4, 6),
                  const pw.PointChartValue(5, 4),
                  const pw.PointChartValue(6, 5),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildSymptomsAndMoodTables() {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('Symptom Patterns'),
              pw.SizedBox(height: 8),
              pw.Table(
                border: pw.TableBorder.all(color: borderCol),
                children: [
                  _buildTableHeader(['Symptom', 'Common Phase', 'Details']),
                  _buildTableRow(['Headache', 'Before period', '1-2 days before']),
                  _buildTableRow(['Bloating', 'Before period', '2-4 days before']),
                  _buildTableRow(['Cramps', 'During period', 'First 1-2 days']),
                  _buildTableRow(['Mood Swings', 'During period', 'First 2 days']),
                ],
              ),
            ],
          ),
        ),
        pw.SizedBox(width: 16),
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('Mood Trends'),
              pw.SizedBox(height: 8),
              pw.Table(
                border: pw.TableBorder.all(color: borderCol),
                children: [
                  _buildTableHeader(['Mood', 'Common Phase', 'Details']),
                  _buildTableRow(['Not Great', 'Before period', '3-5 days before']),
                  _buildTableRow(['Bad', 'During period', 'First 1-2 days']),
                  _buildTableRow(['Great', 'After period', '2-5 days after']),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildLifestyleInsights() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Lifestyle Averages'),
        pw.SizedBox(height: 8),
        pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: borderCol),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _buildInfoCol('Sleep Average', '6.5 hrs/night'),
              _buildInfoCol('Water Intake', '1.5 L/day'),
              _buildInfoCol('Activity Level', 'Moderate'),
              _buildInfoCol('Reported Stress', 'High'),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildObservations() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Clinical Observations Summary'),
        pw.SizedBox(height: 8),
        pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: PdfColor.fromHex('#FAFAFA'),
            border: pw.Border.all(color: borderCol),
          ),
          child: pw.Text(
            'Based on the logged data over 6 cycles, the patient\'s cycle is fairly regular with an average length of 29 days (variation ±2 days). '
            'The patient experiences moderate pain and mood swings primarily during the first few days of menstruation. '
            'High stress levels have been noted recently, correlating with a lower sleep average (6.5 hrs), which may affect overall energy and symptom severity.',
            style: pw.TextStyle(color: textDark, fontSize: 10, lineSpacing: 1.5),
          ),
        ),
      ],
    );
  }

  // --- Helpers ---

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(color: primaryPurple, fontWeight: pw.FontWeight.bold, fontSize: 12),
    );
  }

  static pw.Widget _buildInfoCol(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label, style: pw.TextStyle(color: textSecondary, fontSize: 8)),
        pw.SizedBox(height: 2),
        pw.Text(value, style: pw.TextStyle(color: textDark, fontWeight: pw.FontWeight.bold, fontSize: 10)),
      ],
    );
  }

  static pw.Widget _buildMetricBox(String value, String label) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#F5F5F5'),
        border: pw.Border.all(color: borderCol),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(value, style: pw.TextStyle(color: textDark, fontWeight: pw.FontWeight.bold, fontSize: 12)),
          pw.SizedBox(height: 2),
          pw.Text(label, style: pw.TextStyle(color: textSecondary, fontSize: 8)),
        ],
      ),
    );
  }

  static pw.TableRow _buildTableHeader(List<String> cells) {
    return pw.TableRow(
      decoration: pw.BoxDecoration(color: PdfColor.fromHex('#F5F5F5')),
      children: cells.map((cell) {
        return pw.Padding(
          padding: const pw.EdgeInsets.all(6),
          child: pw.Text(
            cell,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8, color: textDark),
          ),
        );
      }).toList(),
    );
  }

  static pw.TableRow _buildTableRow(List<String> cells) {
    return pw.TableRow(
      children: cells.map((cell) {
        return pw.Padding(
          padding: const pw.EdgeInsets.all(6),
          child: pw.Text(
            cell,
            style: pw.TextStyle(fontSize: 8, color: textDark),
          ),
        );
      }).toList(),
    );
  }
}
